spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10GB
      max-request-size: 10GB

file:
  upload-dir: ./files

jwt:
  secretKey: "This Data Must Be Managed By Secret NOT HERE THIS IS JUST EXAMPLE"

log:
  serverName: "HomeLeisure Upload Server"
  level: ERROR
  slack:
    enabled: true
    webHookUrl: ${SLACK_URL}
    channel: error-report-bot
    userName: "[UPLOAD]ErrorReportBot"
  database:
    enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE